# coding: utf-8

# flake8: noqa
"""
    Nesta Annotation Service

    DBpedia Spotlight Annotation service for large datasets.  Please refer to the <a href=\"https://github.com/nestauk/dap_dv_backends/tree/dev/src/services/annotation\" target=\"_blank\">docs</a> for a complete guide on how to use the service.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from dap_annotation_service.models.inline_response200 import InlineResponse200
from dap_annotation_service.models.inline_response2001 import InlineResponse2001
from dap_annotation_service.models.inline_response2002 import InlineResponse2002
from dap_annotation_service.models.inline_response200_context import InlineResponse200Context
from dap_annotation_service.models.inline_response200_context_progress import InlineResponse200ContextProgress
from dap_annotation_service.models.inline_response200_context_waiting import InlineResponse200ContextWaiting
from dap_annotation_service.models.inline_response404 import InlineResponse404
