# coding: utf-8

"""
    Nesta Annotation Service

    DBpedia Spotlight Annotation service for large datasets.  Please refer to the <a href=\"https://github.com/nestauk/dap_dv_backends/tree/dev/src/services/annotation\" target=\"_blank\">docs</a> for a complete guide on how to use the service.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dap_annotation_service
from dap_annotation_service.models.inline_response200_xstate_context import InlineResponse200XstateContext  # noqa: E501
from dap_annotation_service.rest import ApiException


class TestInlineResponse200XstateContext(unittest.TestCase):
    """InlineResponse200XstateContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200XstateContext(self):
        """Test InlineResponse200XstateContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dap_annotation_service.models.inline_response200_xstate_context.InlineResponse200XstateContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
