# coding: utf-8

"""
    Nesta Annotation Service

    DBpedia Spotlight Annotation service for large datasets.  Please refer to the <a href=\"https://github.com/nestauk/dap_dv_backends/tree/dev/src/services/annotation\" target=\"_blank\">docs</a> for a complete guide on how to use the service.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dap_annotation_service
from dap_annotation_service.api.default_api import DefaultApi  # noqa: E501
from dap_annotation_service.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_es_get(self):
        """Test case for es_get

        Annotate data being hosted on an ElasticSearch index  # noqa: E501
        """
        pass

    def test_progress_id_get(self):
        """Test case for progress_id_get

        Get progress for a given annotation using its ID  # noqa: E501
        """
        pass

    def test_s3_get(self):
        """Test case for s3_get

        Annotate data being hosted on an AWS S3 bucket  # noqa: E501
        """
        pass

    def test_status_get(self):
        """Test case for status_get

        Get current status of Annotation server  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
