# coding: utf-8

"""
    Nesta Annotation Service

    DBpedia Spotlight Annotation service for large datasets.  Please refer to the <a href=\"https://github.com/nestauk/dap_dv_backends/tree/dev/src/services/annotation\" target=\"_blank\">docs</a> for a complete guide on how to use the service.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "dap-annotation-service"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Nesta Annotation Service",
    author_email="",
    url="",
    keywords=["Swagger", "Nesta Annotation Service"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    DBpedia Spotlight Annotation service for large datasets.  Please refer to the &lt;a href&#x3D;\&quot;https://github.com/nestauk/dap_dv_backends/tree/dev/src/services/annotation\&quot; target&#x3D;\&quot;_blank\&quot;&gt;docs&lt;/a&gt; for a complete guide on how to use the service.  # noqa: E501
    """
)
