# coding: utf-8

# flake8: noqa

"""
    Nesta Annotation Service

    DBpedia Spotlight Annotation service for large datasets.  Please refer to the <a href=\"https://github.com/nestauk/dap_dv_backends/tree/dev/src/services/annotation\" target=\"_blank\">docs</a> for a complete guide on how to use the service.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from dap_annotation_service.api.default_api import DefaultApi
# import ApiClient
from dap_annotation_service.api_client import ApiClient
from dap_annotation_service.configuration import Configuration
# import models into sdk package
from dap_annotation_service.models.inline_response200 import InlineResponse200
from dap_annotation_service.models.inline_response2001 import InlineResponse2001
from dap_annotation_service.models.inline_response2002 import InlineResponse2002
from dap_annotation_service.models.inline_response200_xstate_context import InlineResponse200XstateContext
from dap_annotation_service.models.inline_response200_xstate_context_progress import InlineResponse200XstateContextProgress
from dap_annotation_service.models.inline_response200_xstate_context_waiting import InlineResponse200XstateContextWaiting
from dap_annotation_service.models.inline_response404 import InlineResponse404
